// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs54PoRPVRDEYaHHQx-eDKzfXepBbVXqc',
    appId: '1:1050317684258:web:9896dd6d62cd7cee13547b',
    messagingSenderId: '1050317684258',
    projectId: 'flutterfirebasegetx-dc999',
    authDomain: 'flutterfirebasegetx-dc999.firebaseapp.com',
    storageBucket: 'flutterfirebasegetx-dc999.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbB-o_S8tcbKp1oMpWp1TfeVX5dAlJQCE',
    appId: '1:1050317684258:android:b5bf9f49bdab1fe113547b',
    messagingSenderId: '1050317684258',
    projectId: 'flutterfirebasegetx-dc999',
    storageBucket: 'flutterfirebasegetx-dc999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjXHAno3dC5SRQQWPZfwMgx_jfbfqXdNg',
    appId: '1:1050317684258:ios:c31793ab079d63ba13547b',
    messagingSenderId: '1050317684258',
    projectId: 'flutterfirebasegetx-dc999',
    storageBucket: 'flutterfirebasegetx-dc999.appspot.com',
    iosBundleId: 'com.example.videoRecorderFlutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjXHAno3dC5SRQQWPZfwMgx_jfbfqXdNg',
    appId: '1:1050317684258:ios:a4eea0b74c641cd513547b',
    messagingSenderId: '1050317684258',
    projectId: 'flutterfirebasegetx-dc999',
    storageBucket: 'flutterfirebasegetx-dc999.appspot.com',
    iosBundleId: 'com.example.videoRecorderFlutterDemo.RunnerTests',
  );
}
